$ANSIBLE_VAULT;1.1;AES256
34323134336262663865383638613366366466386431393734346166653432346132396133326562
3266303434666131393235656261613635326165386234300a333639633630346333616366663838
36386537663639613462663563663364653936383336393539666166633831373230643638333465
6131656130333066300a363130626366316634303665336538623835346461376631353266326238
66373039336530623966303161336436383062663234316535343635396431323134363530323735
66383338393565666666343033383935636262356663316361623739316663636565653565346261
65353031666662313034356437336332333234373364326365373662663634326165313365313566
35613163316235366430356362346166613138386432643732313066623838323338313038646439
37356437623539663333383830623138363036626664643365623634663434313963626432303063
37333562383664333234633931396432323134656438353030393230323332396261316531653165
36613461396131323134383935386361663239666139303062366531376630383266646564353035
35323666376237373934386662376430393039356135353132306361303032643932313962396335
35346266373536363038336461633066646564666362633435336138366461616163323834633162
65616130633736366638333535656533343939396235666634333665653935613834353565373364
65396561363563383238623439626164343363326662656436333664303636663337343334623330
35626366633033303637366361653232363862663530633263386462616331633736333065366663
64383233323763333535353531313436646538353561353031363037633164316231636661353062
36376436616366303637353766353939623462353730376531626537373739376663363537323531
63636431366363356530343231386362643665313164353832393662663266376539636334343862
32333830353362373764663437663838393638393136343533636364373661623132386335373830
3963
